/**
 * Stable workspace entry point for `@pptx-glimpse/document`.
 *
 * This surface is limited to the PptxSourceModel foundation that current
 * conversion, writer, and minimal editing workflows are allowed to depend on:
 * source model types, the PPTX reader, computed view generation, the writer,
 * and the narrow plain text-run edit operation.
 *
 * Keep parser helpers, raw replacement/editing APIs, writer dirty-scope
 * implementation details, and other OOXML internals behind their owning
 * modules until those contracts are intentionally promoted.
 */

export type {
  ComputedBackground,
  ComputedBlipEffects,
  ComputedCellBorders,
  ComputedChartData,
  ComputedChartElement,
  ComputedChartLegend,
  ComputedChartSeries,
  ComputedChartType,
  ComputedColor,
  ComputedColorChangeEffect,
  ComputedConnectorElement,
  ComputedDiagramDrawing,
  ComputedDiagramDrawingDiagnostic,
  ComputedDuotoneEffect,
  ComputedEffectList,
  ComputedElement,
  ComputedElementLayer,
  ComputedFill,
  ComputedGroupElement,
  ComputedImageElement,
  ComputedOutline,
  ComputedParagraph,
  ComputedPlaceholderMatch,
  ComputedRawElement,
  ComputedRelationship,
  ComputedRunProperties,
  ComputedShapeElement,
  ComputedSlide,
  ComputedSlideSize,
  ComputedSmartArtElement,
  ComputedTableCell,
  ComputedTableData,
  ComputedTableElement,
  ComputedTableRow,
  ComputedTextBody,
  ComputedTextRun,
  CreateComputedViewOptions,
  PptxComputedView,
} from "./computed/index.js";
export { createComputedView } from "./computed/index.js";
export type { ReadPptxInput } from "./reader/index.js";
export { readPptx } from "./reader/index.js";
export type {
  ContentTypeDefault,
  ContentTypeOverride,
  ContentTypes,
  Diagnostic,
  DiagnosticSeverity,
  Emu,
  HundredthPt,
  MediaPart,
  OoxmlAngle,
  OoxmlPercent,
  PackageGraph,
  PackagePartRef,
  PartPath,
  PartRelationships,
  PptxSourceModel,
  PptxSourceModelEdit,
  PptxSourceModelShapeTransformEdit,
  PptxSourceModelTextRunEdit,
  Pt,
  RawOoxmlNode,
  RawPackagePart,
  RawSidecar,
  RawSidecarId,
  Relationship,
  RelationshipId,
  RelationshipTargetMode,
  SlideSize,
  SourceArrowEndpoint,
  SourceArrowSize,
  SourceArrowType,
  SourceAutoNumScheme,
  SourceBackground,
  SourceBiLevelEffect,
  SourceBlipEffects,
  SourceBlurEffect,
  SourceBulletType,
  SourceCellBorders,
  SourceChart,
  SourceColor,
  SourceColorChangeEffect,
  SourceColorMap,
  SourceColorTransform,
  SourceConnector,
  SourceCustomGeometry,
  SourceCustomGeometryPath,
  SourceDashStyle,
  SourceDuotoneEffect,
  SourceEffectList,
  SourceFill,
  SourceGeometry,
  SourceGlow,
  SourceGradient,
  SourceGradientStop,
  SourceGroup,
  SourceHandle,
  SourceImage,
  SourceImageCrop,
  SourceImageFillTile,
  SourceImageStretch,
  SourceInnerShadow,
  SourceLineCap,
  SourceLineJoin,
  SourceLumEffect,
  SourceMasterTextStyles,
  SourceNodeId,
  SourceOuterShadow,
  SourceOutline,
  SourceParagraph,
  SourceParagraphProperties,
  SourcePlaceholder,
  SourcePresentation,
  SourcePresetGeometry,
  SourceRawShapeNode,
  SourceRectangleAlignment,
  SourceRunProperties,
  SourceShape,
  SourceShapeNode,
  SourceShapeStyle,
  SourceSlide,
  SourceSlideLayout,
  SourceSlideMaster,
  SourceSmartArt,
  SourceSoftEdge,
  SourceSpacingValue,
  SourceStyleReference,
  SourceTable,
  SourceTableCell,
  SourceTableColumn,
  SourceTableData,
  SourceTableRow,
  SourceTabStop,
  SourceTextAlign,
  SourceTextAutoFit,
  SourceTextBody,
  SourceTextBodyProperties,
  SourceTextRun,
  SourceTextStyle,
  SourceTextVerticalType,
  SourceTextWrap,
  SourceTheme,
  SourceThemeColorScheme,
  SourceThemeFontScheme,
  SourceThemeFormatScheme,
  SourceTransform,
  SourceVerticalAnchor,
  UpdateShapeTransformInput,
} from "./source/index.js";
export {
  findShapeNodeBySourceHandle,
  findTextRunBySourceHandle,
  replaceTextRunPlainText,
  updateShapeTransform,
} from "./source/index.js";
export {
  asEmu,
  asHundredthPt,
  asOoxmlAngle,
  asOoxmlPercent,
  asPartPath,
  asPt,
  asRawSidecarId,
  asRelationshipId,
  asSourceNodeId,
} from "./source/index.js";
export type { WritePptxOutput } from "./writer/index.js";
export { writePptx } from "./writer/index.js";
