export type {
  CleanDocComputedView,
  ComputedBackground,
  ComputedCellBorders,
  ComputedChartElement,
  ComputedColor,
  ComputedConnectorElement,
  ComputedElement,
  ComputedElementLayer,
  ComputedFill,
  ComputedGroupElement,
  ComputedImageElement,
  ComputedOutline,
  ComputedParagraph,
  ComputedPlaceholderMatch,
  ComputedRawElement,
  ComputedRelationship,
  ComputedRunProperties,
  ComputedShapeElement,
  ComputedSlide,
  ComputedSlideSize,
  ComputedSmartArtElement,
  ComputedTableCell,
  ComputedTableData,
  ComputedTableElement,
  ComputedTableRow,
  ComputedTextBody,
  ComputedTextRun,
  CreateComputedViewOptions,
} from "./clean-doc-computed-view.js";
export { createComputedView } from "./create-computed-view.js";
