export { createComputedView } from "./create-computed-view.js";
export type {
  ComputedBackground,
  ComputedBlipEffects,
  ComputedCellBorders,
  ComputedChartElement,
  ComputedColor,
  ComputedColorChangeEffect,
  ComputedConnectorElement,
  ComputedDiagramDrawing,
  ComputedDiagramDrawingDiagnostic,
  ComputedDuotoneEffect,
  ComputedEffectList,
  ComputedElement,
  ComputedElementLayer,
  ComputedFill,
  ComputedGroupElement,
  ComputedImageElement,
  ComputedOutline,
  ComputedParagraph,
  ComputedPlaceholderMatch,
  ComputedRawElement,
  ComputedRelationship,
  ComputedRunProperties,
  ComputedShapeElement,
  ComputedSlide,
  ComputedSlideSize,
  ComputedSmartArtElement,
  ComputedTableCell,
  ComputedTableData,
  ComputedTableElement,
  ComputedTableRow,
  ComputedTextBody,
  ComputedTextRun,
  CreateComputedViewOptions,
  PptxComputedView,
} from "./pptx-computed-view.js";
