/**
 * Barrel re-export of type PptxSourceModel source model.
 */

export type { PptxAuthoringTarget } from "./authoring-session.js";
export { createPptxAuthoringSession, PptxAuthoringSession } from "./authoring-session.js";
export type { CrossPartHandleMapping } from "./cross-part-move-planning.js";
export type {
  MoveShapesAcrossSlidesOptions,
  MoveShapesAcrossSlidesResult,
} from "./cross-slide-drawing-move.js";
export { moveShapesAcrossSlides } from "./cross-slide-drawing-move.js";
export type { Diagnostic, DiagnosticSeverity } from "./diagnostics.js";
export type {
  AddChartAreaStyleInput,
  AddChartAxisInput,
  AddChartCategoryAxisInput,
  AddChartColorInput,
  AddChartDataPointInput,
  AddChartFillInput,
  AddChartInput,
  AddChartMarkerInput,
  AddChartNumberFormatInput,
  AddChartOutlineInput,
  AddChartPlotLayoutInput,
  AddChartSeriesInput,
  AddChartTextStyleInput,
  AddConnectorConnectionEndpointInput,
  AddConnectorInput,
  AddConnectorOutlineInput,
  AddEmptySlideFromLayoutInput,
  AddInnerShadowInput,
  AddOuterShadowInput,
  AddPictureCropInput,
  AddPictureEffectsInput,
  AddPictureInput,
  AddPlaceholderInput,
  AddShapeBodyPropertiesInput,
  AddShapeColorInput,
  AddShapeColorTransformInput,
  AddShapeCustomGeometryInput,
  AddShapeCustomGeometryPathCommandInput,
  AddShapeCustomGeometryPathInput,
  AddShapeEffectsInput,
  AddShapeFillInput,
  AddShapeGeometryInput,
  AddShapeGlowInput,
  AddShapeGradientFillInput,
  AddShapeGradientStopInput,
  AddShapeInput,
  AddShapeOutlineInput,
  AddShapeParagraphInput,
  AddShapeParagraphPropertiesInput,
  AddShapePresetGeometryInput,
  AddShapeRunInput,
  AddShapeRunPropertiesInput,
  AddSlideLayoutBackgroundInput,
  AddSlideLayoutInput,
  AddSlideLayoutMarginInput,
  AddSlideNumberInput,
  AddTableBorderInput,
  AddTableCellInput,
  AddTableInput,
  AddTableRowInput,
  AddTableRunInput,
  AddTableRunPropertiesInput,
  AddTextBoxBaselineInput,
  AddTextBoxBodyPropertiesInput,
  AddTextBoxBulletInput,
  AddTextBoxColorInput,
  AddTextBoxColorTransformInput,
  AddTextBoxGlowInput,
  AddTextBoxGradientFillInput,
  AddTextBoxGradientStopInput,
  AddTextBoxInput,
  AddTextBoxLineSpacingInput,
  AddTextBoxOutlineInput,
  AddTextBoxParagraphInput,
  AddTextBoxParagraphPropertiesInput,
  AddTextBoxRunInput,
  AddTextBoxRunPropertiesInput,
  AddTextBoxUnderlineInput,
  AddTextBoxUnderlineStyle,
  CloneSlideLayoutInput,
  EditableTableCellBorder,
  EditableTableCellProperties,
  EditableTableCellProperty,
  MoveSlideInput,
  NativeChartLabelPosition,
  NativeChartLegendPosition,
  NativeChartMarkerSymbol,
  NativeChartTickMark,
  NativeChartType,
  NativeRadarStyle,
  PlaceholderType,
  SetPictureCropInput,
  SlideLayoutType,
  TableCellAddress,
  UpdateBubbleChartDataInput,
  UpdateBubbleChartSeriesDataInput,
  UpdateCategoryChartSeriesSource,
  UpdateChartDataInput,
  UpdateChartSeriesDataInput,
  UpdateScatterChartDataInput,
  UpdateScatterChartSeriesDataInput,
  UpdateShapeTransformInput,
  UpdateThemeColorSchemeInput,
  UpdateThemeFontSchemeInput,
  UpdateThemeFontSetInput,
  UpdateThemeSchemeInput,
} from "./editing.js";
export {
  addChart,
  addConnector,
  addEmptySlideFromLayout,
  addPicture,
  addPlaceholder,
  addShape,
  addSlideLayout,
  addSlideNumber,
  addTable,
  addTextBox,
  clearParagraphProperties,
  clearPictureCrop,
  clearTableCellProperties,
  clearTextRunProperties,
  cloneSlideLayout,
  countImageReferencesToMedia,
  deleteShape,
  deleteSlide,
  duplicateSlide,
  findParagraphBySourceHandle,
  findShapeNodeBySourceHandle,
  findTextRunBySourceHandle,
  moveSlide,
  replaceImageBytes,
  replaceParagraphPlainText,
  replaceTextRunPlainText,
  setParagraphProperties,
  setPictureCrop,
  setShapeFill,
  setShapeOutline,
  setTableCellProperties,
  setTextRunProperties,
  updateBubbleChartData,
  updateChartData,
  updateScatterChartData,
  updateShapeTransform,
  updateThemeScheme,
} from "./editing.js";
export type {
  PartPath,
  RawSidecarId,
  RelationshipId,
  SourceHandle,
  SourceNodeId,
} from "./handles.js";
export { asPartPath, asRawSidecarId, asRelationshipId, asSourceNodeId } from "./handles.js";
export type {
  ContentTypeDefault,
  ContentTypeOverride,
  ContentTypes,
  MediaPart,
  PackageGraph,
  PackagePartRef,
  PartRelationships,
  Relationship,
  RelationshipTargetMode,
} from "./package-graph.js";
export type {
  ConnectorPresetGeometry,
  EditableParagraphProperties,
  EditableParagraphProperty,
  EditableShapeFill,
  EditableShapeOutline,
  EditableTextRunProperties,
  EditableTextRunProperty,
  PptxSourceModel,
  PptxSourceModelAddChartEdit,
  PptxSourceModelAddConnectorEdit,
  PptxSourceModelAddEmptySlideFromLayoutEdit,
  PptxSourceModelAddPictureEdit,
  PptxSourceModelAddShapeEdit,
  PptxSourceModelAddSlideLayoutEdit,
  PptxSourceModelAddTableEdit,
  PptxSourceModelAddTextBoxEdit,
  PptxSourceModelCloneSlideLayoutEdit,
  PptxSourceModelDeleteShapeEdit,
  PptxSourceModelDeleteSlideEdit,
  PptxSourceModelDuplicateSlideEdit,
  PptxSourceModelEdit,
  PptxSourceModelGroupShapesEdit,
  PptxSourceModelMoveShapesAcrossSlidesEdit,
  PptxSourceModelMoveShapesEdit,
  PptxSourceModelMoveSlideEdit,
  PptxSourceModelParagraphPropertiesEdit,
  PptxSourceModelParagraphTextEdit,
  PptxSourceModelPictureCropEdit,
  PptxSourceModelReorderShapesEdit,
  PptxSourceModelReplaceImageEdit,
  PptxSourceModelSetBackgroundEdit,
  PptxSourceModelSetSlideBackgroundEdit,
  PptxSourceModelShapeFillEdit,
  PptxSourceModelShapeOutlineEdit,
  PptxSourceModelShapeTransformEdit,
  PptxSourceModelTableCellPropertiesEdit,
  PptxSourceModelTextRunEdit,
  PptxSourceModelTextRunPropertiesEdit,
  PptxSourceModelUngroupShapeEdit,
  PptxSourceModelUpdateBubbleChartDataEdit,
  PptxSourceModelUpdateChartDataEdit,
  PptxSourceModelUpdateScatterChartDataEdit,
  PptxSourceModelUpdateThemeSchemeEdit,
} from "./pptx-source-model.js";
export type {
  SlideSize,
  SourceBackground,
  SourceColorMap,
  SourceMasterTextStyles,
  SourcePresentation,
  SourceSlide,
  SourceSlideLayout,
  SourceSlideMaster,
  SourceTheme,
  SourceThemeColorScheme,
  SourceThemeFontScheme,
  SourceThemeFormatScheme,
} from "./presentation.js";
export type { RawOoxmlNode, RawPackagePart, RawSidecar } from "./raw.js";
export { groupShapes, ungroupShape } from "./shape-grouping.js";
export type { MoveShapesOptions } from "./shape-moving.js";
export { moveShapes } from "./shape-moving.js";
export { reorderShapes } from "./shape-ordering.js";
export type {
  SourceArrowEndpoint,
  SourceArrowSize,
  SourceArrowType,
  SourceAutoNumScheme,
  SourceBiLevelEffect,
  SourceBlipEffects,
  SourceBlurEffect,
  SourceBulletType,
  SourceCellBorders,
  SourceChart,
  SourceColor,
  SourceColorChangeEffect,
  SourceColorTransform,
  SourceConnector,
  SourceConnectorConnection,
  SourceConnectorConnectionEndpoint,
  SourceCustomGeometry,
  SourceCustomGeometryPath,
  SourceDashStyle,
  SourceDuotoneEffect,
  SourceEffectList,
  SourceFill,
  SourceGeometry,
  SourceGlow,
  SourceGradient,
  SourceGradientStop,
  SourceGroup,
  SourceImage,
  SourceImageCrop,
  SourceImageFillTile,
  SourceImageStretch,
  SourceInnerShadow,
  SourceLineCap,
  SourceLineJoin,
  SourceLumEffect,
  SourceOuterShadow,
  SourceOutline,
  SourceParagraph,
  SourceParagraphProperties,
  SourcePictureBlipFillMode,
  SourcePlaceholder,
  SourcePresetGeometry,
  SourceRawShapeNode,
  SourceRectangleAlignment,
  SourceRunProperties,
  SourceShape,
  SourceShapeNode,
  SourceShapeStyle,
  SourceSmartArt,
  SourceSoftEdge,
  SourceSpacingValue,
  SourceStyleReference,
  SourceTable,
  SourceTableCell,
  SourceTableColumn,
  SourceTableData,
  SourceTableRow,
  SourceTabStop,
  SourceTextAlign,
  SourceTextAutoFit,
  SourceTextBody,
  SourceTextBodyProperties,
  SourceTextRun,
  SourceTextStyle,
  SourceTextVerticalType,
  SourceTextWrap,
  SourceTransform,
  SourceUnderlineStyle,
  SourceVerticalAnchor,
} from "./shapes.js";
export type {
  BackgroundColorInput,
  BackgroundGradientStopInput,
  SetBackgroundInput,
  SetSlideBackgroundInput,
  SlideBackgroundColorInput,
  SlideBackgroundGradientStopInput,
} from "./slide-background-authoring.js";
export {
  clearBackground,
  setBackground,
  setSlideBackground,
} from "./slide-background-authoring.js";
export type { Emu, HundredthPt, OoxmlAngle, OoxmlPercent, Pt } from "./units.js";
export { asEmu, asHundredthPt, asOoxmlAngle, asOoxmlPercent, asPt } from "./units.js";
