/**
 * PptxSourceModel source model 型の barrel re-export。
 */

export type { Diagnostic, DiagnosticSeverity } from "./diagnostics.js";
export { findTextRunBySourceHandle, replaceTextRunPlainText } from "./editing.js";
export type {
  PartPath,
  RawSidecarId,
  RelationshipId,
  SourceHandle,
  SourceNodeId,
} from "./handles.js";
export { asPartPath, asRawSidecarId, asRelationshipId, asSourceNodeId } from "./handles.js";
export type {
  ContentTypeDefault,
  ContentTypeOverride,
  ContentTypes,
  MediaPart,
  PackageGraph,
  PackagePartRef,
  PartRelationships,
  Relationship,
  RelationshipTargetMode,
} from "./package-graph.js";
export type {
  PptxSourceModel,
  PptxSourceModelEdit,
  PptxSourceModelTextRunEdit,
} from "./pptx-source-model.js";
export type {
  SlideSize,
  SourceBackground,
  SourceColorMap,
  SourceMasterTextStyles,
  SourcePresentation,
  SourceSlide,
  SourceSlideLayout,
  SourceSlideMaster,
  SourceTheme,
  SourceThemeColorScheme,
  SourceThemeFontScheme,
  SourceThemeFormatScheme,
} from "./presentation.js";
export type { RawOoxmlNode, RawPackagePart, RawSidecar } from "./raw.js";
export type {
  SourceArrowEndpoint,
  SourceArrowSize,
  SourceArrowType,
  SourceAutoNumScheme,
  SourceBiLevelEffect,
  SourceBlipEffects,
  SourceBlurEffect,
  SourceBulletType,
  SourceCellBorders,
  SourceChart,
  SourceColor,
  SourceColorChangeEffect,
  SourceColorTransform,
  SourceConnector,
  SourceCustomGeometry,
  SourceCustomGeometryPath,
  SourceDashStyle,
  SourceDuotoneEffect,
  SourceEffectList,
  SourceFill,
  SourceGeometry,
  SourceGlow,
  SourceGradient,
  SourceGradientStop,
  SourceGroup,
  SourceImage,
  SourceImageCrop,
  SourceImageFillTile,
  SourceImageStretch,
  SourceInnerShadow,
  SourceLineCap,
  SourceLineJoin,
  SourceLumEffect,
  SourceOuterShadow,
  SourceOutline,
  SourceParagraph,
  SourceParagraphProperties,
  SourcePlaceholder,
  SourcePresetGeometry,
  SourceRawShapeNode,
  SourceRectangleAlignment,
  SourceRunProperties,
  SourceShape,
  SourceShapeNode,
  SourceShapeStyle,
  SourceSmartArt,
  SourceSoftEdge,
  SourceSpacingValue,
  SourceStyleReference,
  SourceTable,
  SourceTableCell,
  SourceTableColumn,
  SourceTableData,
  SourceTableRow,
  SourceTabStop,
  SourceTextAlign,
  SourceTextAutoFit,
  SourceTextBody,
  SourceTextBodyProperties,
  SourceTextRun,
  SourceTextStyle,
  SourceTextVerticalType,
  SourceTextWrap,
  SourceTransform,
  SourceVerticalAnchor,
} from "./shapes.js";
export type { Emu, HundredthPt, OoxmlAngle, OoxmlPercent, Pt } from "./units.js";
export { asEmu, asHundredthPt, asOoxmlAngle, asOoxmlPercent, asPt } from "./units.js";
