export type CapabilityStatus =
  | { readonly kind: "supported"; readonly evidence: readonly string[] }
  | { readonly kind: "intentional"; readonly reason: string }
  | { readonly kind: "tracked"; readonly issue: number; readonly reason: string };

export interface EditorCapability {
  readonly capability: string;
  readonly documentApis: readonly string[];
  readonly editorCommands: readonly string[];
  readonly coreMembers: readonly string[];
  readonly uiCommandKinds: readonly string[];
  readonly uiCoreMembers: readonly string[];
  readonly document: CapabilityStatus;
  readonly editor: CapabilityStatus;
  readonly core: CapabilityStatus;
  readonly ui: CapabilityStatus;
}

const supported = (...evidence: string[]): CapabilityStatus => ({ kind: "supported", evidence });
const intentional = (reason: string): CapabilityStatus => ({ kind: "intentional", reason });
const tracked = (issue: number, reason: string): CapabilityStatus => ({
  kind: "tracked",
  issue,
  reason,
});

const DOCUMENT_ROOT = "packages/document/src/index.ts";
const EDITOR_ROOT = "packages/editor/src/index.ts";
const CORE_SESSION = "packages/core/src/pptx-editor-session.ts";
const REACT_EDITOR = "packages/editor-react/src/PptxEditor.tsx";

export const EDITOR_CAPABILITIES: readonly EditorCapability[] = [
  {
    capability: "Presentation authoring",
    documentApis: ["createPptx", "createPptxAuthoringSession"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("From-scratch presentation construction stays in the document layer."),
    core: intentional("Core edits an already opened presentation."),
    ui: intentional("The reusable editor UI edits a consumer-owned session."),
  },
  {
    capability: "Text run content and formatting",
    documentApis: ["replaceTextRunPlainText", "setTextRunProperties", "clearTextRunProperties"],
    editorCommands: ["replaceTextRunPlainText", "setTextRunProperties", "clearTextRunProperties"],
    coreMembers: [],
    uiCommandKinds: ["replaceTextRunPlainText", "setTextRunProperties", "clearTextRunProperties"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Paragraph content and formatting",
    documentApis: [
      "replaceParagraphPlainText",
      "setParagraphProperties",
      "clearParagraphProperties",
    ],
    editorCommands: [
      "replaceParagraphPlainText",
      "setParagraphProperties",
      "clearParagraphProperties",
    ],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: intentional("The reusable UI edits text through run-level operations only."),
  },
  {
    capability: "Shape transform",
    documentApis: ["updateShapeTransform"],
    editorCommands: ["moveShape", "resizeShape", "setShapeTransform"],
    coreMembers: [],
    uiCommandKinds: ["setShapeTransform"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Shape fill and outline",
    documentApis: ["setShapeFill", "setShapeOutline"],
    editorCommands: ["setShapeFill", "setShapeOutline"],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: intentional("The current toolbar exposes text formatting, not general shape styling."),
  },
  {
    capability: "Generic drawing authoring (shape/picture/table/chart)",
    documentApis: ["addShape", "addPicture", "addTable", "addChart"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("The command layer exposes focused interactive authoring operations only."),
    core: intentional("Generic document construction remains a lower-level document workflow."),
    ui: intentional("A general-purpose drawing insertion UI is outside the reusable editor scope."),
  },
  {
    capability: "Text box authoring",
    documentApis: ["addTextBox"],
    editorCommands: ["addTextBox"],
    coreMembers: ["addTextBox"],
    uiCommandKinds: [],
    uiCoreMembers: ["addTextBox"],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#addTextBox`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Connector authoring",
    documentApis: ["addConnector"],
    editorCommands: ["addConnector"],
    coreMembers: ["addConnector"],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#addConnector`),
    ui: intentional("The current toolbar has no connector insertion control."),
  },
  {
    capability: "Delete drawing",
    documentApis: ["deleteShape"],
    editorCommands: ["deleteShape"],
    coreMembers: ["deleteSelectedShape", "deleteShape"],
    uiCommandKinds: ["deleteShape"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#deleteShape`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Group / ungroup",
    documentApis: ["groupShapes", "ungroupShape"],
    editorCommands: ["groupShapes", "ungroupShape"],
    coreMembers: ["groupShapes", "ungroupShape"],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#groupShapes`, `${CORE_SESSION}#ungroupShape`),
    ui: tracked(818, "Multiple selection and group/ungroup UI are planned."),
  },
  {
    capability: "Move drawings within/across containers",
    documentApis: ["moveShapes", "moveShapesAcrossSlides"],
    editorCommands: ["moveShapes", "moveShapesAcrossSlides"],
    coreMembers: ["moveShapes", "moveShapesAcrossSlides"],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#moveShapes`, `${CORE_SESSION}#moveShapesAcrossSlides`),
    ui: intentional("Direct manipulation currently moves one shape; container transfer has no UI."),
  },
  {
    capability: "Drawing reorder",
    documentApis: ["reorderShapes"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("Editor uses partial move commands instead of the complete-order API."),
    core: intentional("Core follows the editor partial-move contract."),
    ui: intentional("Drawing z-order controls are not part of the current UI."),
  },
  {
    capability: "Replace picture media",
    documentApis: ["replaceImageBytes"],
    editorCommands: ["replaceImage"],
    coreMembers: [],
    uiCommandKinds: ["replaceImage"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Picture crop",
    documentApis: ["setPictureCrop", "clearPictureCrop"],
    editorCommands: ["setPictureCrop", "clearPictureCrop"],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: intentional("Picture crop controls have not been adopted by the reusable UI."),
  },
  {
    capability: "Table cell properties",
    documentApis: ["setTableCellProperties", "clearTableCellProperties"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: tracked(846, "Table cell/range commands are planned with the React table editor."),
    core: tracked(846, "Public-session table editing is part of the tracked integration."),
    ui: tracked(846, "Table cell selection and editing UI are planned."),
  },
  {
    capability: "Chart data",
    documentApis: ["updateChartData", "updateScatterChartData", "updateBubbleChartData"],
    editorCommands: ["updateChartData", "updateScatterChartData", "updateBubbleChartData"],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: tracked(847, "Chart data and formatting UI are planned."),
  },
  {
    capability: "Slide/master/layout background",
    documentApis: ["setBackground", "clearBackground", "setSlideBackground"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: tracked(848, "Background commands are planned."),
    core: tracked(848, "Affected-slide rendering for background edits is planned."),
    ui: tracked(848, "Background source display and editing UI are planned."),
  },
  {
    capability: "Theme color/font scheme",
    documentApis: ["updateThemeScheme"],
    editorCommands: ["updateThemeScheme"],
    coreMembers: ["updateThemeScheme"],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#updateThemeScheme`),
    ui: intentional("Theme scheme controls are not part of the current editor UI."),
  },
  {
    capability: "Add slide from layout",
    documentApis: ["addEmptySlideFromLayout"],
    editorCommands: ["addEmptySlideFromLayout"],
    coreMembers: [],
    uiCommandKinds: ["addEmptySlideFromLayout"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Slide duplicate/move/delete",
    documentApis: ["duplicateSlide", "moveSlide", "deleteSlide"],
    editorCommands: ["duplicateSlide", "moveSlide", "deleteSlide"],
    coreMembers: [],
    uiCommandKinds: ["duplicateSlide", "moveSlide", "deleteSlide"],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: supported(EDITOR_ROOT),
    core: supported(`${CORE_SESSION}#apply`),
    ui: supported(REACT_EDITOR),
  },
  {
    capability: "Layout authoring / cloning",
    documentApis: ["addSlideLayout", "cloneSlideLayout"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("Template authoring remains a document-layer workflow."),
    core: intentional("Core exposes template catalog/preview, not template construction."),
    ui: intentional("The layout picker consumes existing layouts only."),
  },
  {
    capability: "Placeholder authoring",
    documentApis: ["addPlaceholder"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("Placeholder construction remains a document-layer workflow."),
    core: intentional("Core does not materialize template placeholders."),
    ui: intentional("The reusable UI does not author master/layout placeholders."),
  },
  {
    capability: "Slide-number placeholder authoring",
    documentApis: ["addSlideNumber"],
    editorCommands: [],
    coreMembers: [],
    uiCommandKinds: [],
    uiCoreMembers: [],
    document: supported(DOCUMENT_ROOT),
    editor: intentional("Template placeholder construction remains in the document layer."),
    core: intentional("Core does not author template placeholders."),
    ui: intentional("The reusable UI does not author slide-number placeholders."),
  },
] as const;

export const DOCUMENT_NON_CAPABILITY_EXPORTS = [
  "PptxAuthoringSession",
  "asEmu",
  "asHundredthPt",
  "asOoxmlAngle",
  "asOoxmlPercent",
  "asPartPath",
  "asPt",
  "asRawSidecarId",
  "asRelationshipId",
  "asSourceNodeId",
  "countImageReferencesToMedia",
  "createComputedTemplateView",
  "createComputedView",
  "findParagraphBySourceHandle",
  "findShapeNodeBySourceHandle",
  "findTextRunBySourceHandle",
  "readPptx",
  "writePptx",
] as const;

export const CORE_SESSION_NON_CAPABILITY_MEMBERS = [
  "apply",
  "applyAll",
  "create",
  "document",
  "history",
  "layoutCatalog",
  "previewLayoutCatalogTarget",
  "redo",
  "renderCurrentSlides",
  "response",
  "save",
  "selectShape",
  "selection",
  "shapes",
  "slides",
  "undo",
] as const;
