import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, posix, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import {
  formatGeneratedEditorCommand,
  formatNavigationTitle,
  inlineGeneratedConvertOptions,
  isValidNavigationPath,
  navigationPathParts,
  normalizeGeneratedMarkdownLinks,
} from "./api-reference-generation.js";

interface NavigationItem {
  readonly title: string;
  readonly path?: string;
  readonly children?: readonly NavigationItem[];
}

interface LandingSection {
  readonly title: string;
  readonly description: string;
  readonly symbols: readonly {
    readonly entryPoint: "node" | "browser";
    readonly name: string;
  }[];
}

const landingSections: readonly LandingSection[] = [
  {
    title: "Conversion",
    description: "Convert PPTX bytes or an existing source model to SVG or PNG output.",
    symbols: [
      { entryPoint: "node", name: "convertPptxToSvg" },
      { entryPoint: "node", name: "convertPptxToPng" },
      { entryPoint: "node", name: "renderPptxSourceModelToSvg" },
      { entryPoint: "node", name: "collectUsedFonts" },
      { entryPoint: "node", name: "ConvertOptions" },
    ],
  },
  {
    title: "Editing",
    description: "Create an editor session, apply commands, inspect results, and save a PPTX.",
    symbols: [
      { entryPoint: "node", name: "createPptxEditorSession" },
      { entryPoint: "node", name: "PptxEditorSession" },
      { entryPoint: "node", name: "EditorCommand" },
      { entryPoint: "node", name: "PptxEditorError" },
    ],
  },
  {
    title: "Fonts",
    description: "Configure font mapping, font buffers, caches, and text measurement.",
    symbols: [
      { entryPoint: "node", name: "createFontMapping" },
      { entryPoint: "node", name: "FontMapping" },
      { entryPoint: "node", name: "createOpentypeSetupFromBuffers" },
      { entryPoint: "node", name: "clearFontCache" },
    ],
  },
  {
    title: "Reports and diagnostics",
    description: "Inspect converted slides, diagnostics, warnings, and support coverage.",
    symbols: [
      { entryPoint: "node", name: "SvgConversionReport" },
      { entryPoint: "node", name: "PngConversionReport" },
      { entryPoint: "node", name: "ConversionDiagnostic" },
      { entryPoint: "node", name: "SupportCoverage" },
      { entryPoint: "node", name: "getWarningSummary" },
    ],
  },
  {
    title: "Browser-specific API",
    description: "Use browser entry-point signatures and initialize PNG WebAssembly support.",
    symbols: [
      { entryPoint: "browser", name: "convertPptxToSvg" },
      { entryPoint: "browser", name: "convertPptxToPng" },
      { entryPoint: "browser", name: "renderPptxSourceModelToSvg" },
      { entryPoint: "browser", name: "initResvgWasm" },
      { entryPoint: "browser", name: "ResvgWasmInput" },
    ],
  },
];

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const contentDirectory = join(repositoryRoot, "demo/src/content");
const navigationPath = join(contentDirectory, "navigation.json");
const entriesByDirectory = new Map<string, Map<string, unknown>>();
const navigation = parseNavigation(JSON.parse(await readFile(navigationPath, "utf8")));

await writeLandingPage();
await removeBrowserReexportList();
await inlineConvertOptions();
await formatEditorCommandPage();
await normalizeGeneratedLinks(contentDirectory);

addEntry("", "index", { title: "API Reference", display: "hidden" });
await addLandingNavigation();
addEntry("", "node", { title: "Node.js API", display: "hidden" });
addEntry("", "browser", { title: "Browser-specific API", display: "hidden" });

for (const item of navigation) {
  collectNavigation(item);
}

for (const [directory, entries] of entriesByDirectory) {
  const outputDirectory = resolve(contentDirectory, directory);
  if (
    outputDirectory !== contentDirectory &&
    !outputDirectory.startsWith(`${contentDirectory}${sep}`)
  ) {
    throw new Error(`Refusing to write API navigation metadata outside ${contentDirectory}`);
  }
  await mkdir(outputDirectory, { recursive: true });
  const source = `// Generated by scripts/generate-api-reference-meta.ts. Do not edit.\nexport default ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n`;
  await writeFile(join(outputDirectory, "_meta.ts"), source);
}

async function writeLandingPage(): Promise<void> {
  const sections = landingSections.map((section) => {
    const links = section.symbols.map(({ entryPoint, name }) => {
      const path = findSymbolPath(entryPoint, name);
      return `- [\`${name}\`](/docs/api/${path.slice(0, -extname(path).length)})`;
    });
    return `## ${section.title}\n\n${section.description}\n\n${links.join("\n")}`;
  });

  await writeFile(
    join(contentDirectory, "index.mdx"),
    `# API Reference

This index is generated from the public Node.js and browser entry points. Choose an API by task,
then open its generated page for the complete signature, options, return value, and related types.

${sections.join("\n\n")}\n`,
  );
}

async function addLandingNavigation(): Promise<void> {
  for (const section of landingSections) {
    const key = section.title.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-");
    addEntry("", key, {
      title: section.title,
      theme: {
        collapsed: true,
      },
    });
    addEntry(key, "index", { title: section.title, display: "hidden" });

    const links = section.symbols.map(({ entryPoint, name }) => {
      const path = findSymbolPath(entryPoint, name);
      const href = `/docs/api/${path.slice(0, -extname(path).length)}`;
      addEntry(key, `${entryPoint}-${name}`, { title: name, href });
      return `- [\`${name}\`](${href})`;
    });

    const directory = join(contentDirectory, key);
    await mkdir(directory, { recursive: true });
    await writeFile(
      join(directory, "index.mdx"),
      `# ${section.title}

${section.description}

${links.join("\n")}
`,
    );
  }
}

async function removeBrowserReexportList(): Promise<void> {
  const path = join(contentDirectory, "browser/index.mdx");
  const source = await readFile(path, "utf8");
  await writeFile(path, source.split("\n## References\n", 1)[0]);
}

async function inlineConvertOptions(): Promise<void> {
  const optionsPath = join(contentDirectory, "node/interfaces/ConvertOptions.mdx");
  const optionsSource = await readFile(optionsPath, "utf8");
  const propertiesStart = optionsSource.indexOf("\n## Properties\n");
  if (propertiesStart === -1) {
    throw new Error("Unable to find generated ConvertOptions properties");
  }

  const properties = optionsSource.slice(propertiesStart + "\n## Properties\n".length).trim();
  const targets = [
    "node/functions/convertPptxToSvg.mdx",
    "node/functions/convertPptxToPng.mdx",
    "node/functions/renderPptxSourceModelToSvg.mdx",
    "browser/functions/convertPptxToSvg.mdx",
    "browser/functions/convertPptxToPng.mdx",
    "browser/functions/renderPptxSourceModelToSvg.mdx",
  ];

  for (const target of targets) {
    const path = join(contentDirectory, target);
    const source = await readFile(path, "utf8");
    try {
      await writeFile(path, inlineGeneratedConvertOptions(source, properties));
    } catch (error) {
      throw new Error(`Unable to inline ConvertOptions in ${target}`, { cause: error });
    }
  }
}

async function formatEditorCommandPage(): Promise<void> {
  const path = join(contentDirectory, "node/type-aliases/EditorCommand.mdx");
  const source = await readFile(path, "utf8");
  await writeFile(path, formatGeneratedEditorCommand(source));
}

async function normalizeGeneratedLinks(directory: string): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      await normalizeGeneratedLinks(path);
    } else if (entry.isFile() && extname(entry.name) === ".mdx") {
      const source = await readFile(path, "utf8");
      const normalized = normalizeGeneratedMarkdownLinks(source);
      await writeFile(path, normalized);
    }
  }
}

function findSymbolPath(entryPoint: "node" | "browser", symbolName: string): string {
  const match = flattenNavigation(navigation).find(
    (item) =>
      item.path?.startsWith(`${entryPoint}/`) &&
      posix.basename(item.path, posix.extname(item.path)) === symbolName,
  );
  if (match?.path === undefined) {
    throw new Error(`Unable to find ${entryPoint} API symbol ${symbolName} in TypeDoc navigation`);
  }
  return match.path;
}

function flattenNavigation(items: readonly NavigationItem[]): readonly NavigationItem[] {
  return items.flatMap((item) => [item, ...flattenNavigation(item.children ?? [])]);
}

function collectNavigation(item: NavigationItem): void {
  if (item.path !== undefined) {
    addPath(item.path, formatNavigationTitle(item.title, item.path));
  } else {
    const firstChildPath = item.children?.find((child) => child.path !== undefined)?.path;
    if (firstChildPath !== undefined) {
      const groupDirectory = posix.dirname(firstChildPath);
      addEntry(
        posix.dirname(groupDirectory),
        posix.basename(groupDirectory),
        formatNavigationTitle(item.title),
      );
    }
  }

  for (const child of item.children ?? []) {
    collectNavigation(child);
  }
}

function addPath(path: string, title: string): void {
  const { directory, name } = navigationPathParts(path);

  addEntry(directory === "." ? "" : directory, name, title);
  if (name === "index" && directory !== ".") {
    const parent = posix.dirname(directory);
    const entryPoint = posix.basename(directory);
    addEntry(
      parent === "." ? "" : parent,
      entryPoint,
      entryPoint === "node"
        ? { title: "Node.js API", display: "hidden" }
        : { title: "Browser-specific API", display: "hidden" },
    );
  }
}

function addEntry(directory: string, name: string, title: unknown): void {
  let entries = entriesByDirectory.get(directory);
  if (entries === undefined) {
    entries = new Map();
    entriesByDirectory.set(directory, entries);
  }
  entries.set(name, title);
}

function parseNavigation(value: unknown): readonly NavigationItem[] {
  if (!Array.isArray(value) || !value.every(isNavigationItem)) {
    throw new Error(`Invalid TypeDoc navigation JSON at ${navigationPath}`);
  }
  return value;
}

function isNavigationItem(value: unknown): value is NavigationItem {
  if (typeof value !== "object" || value === null || !("title" in value)) {
    return false;
  }
  if (typeof value.title !== "string") {
    return false;
  }
  if ("path" in value && value.path !== undefined && typeof value.path !== "string") {
    return false;
  }
  if ("path" in value && value.path !== undefined && !isValidNavigationPath(value.path)) {
    return false;
  }
  if ("children" in value && value.children !== undefined) {
    return Array.isArray(value.children) && value.children.every(isNavigationItem);
  }
  return true;
}
