import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, posix, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import {
  formatNavigationTitle,
  isValidNavigationPath,
  navigationPathParts,
  normalizeGeneratedMarkdownLinks,
} from "./api-reference-generation.js";

interface NavigationItem {
  readonly title: string;
  readonly path?: string;
  readonly children?: readonly NavigationItem[];
}

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const contentDirectory = join(repositoryRoot, "demo/src/content");
const navigationPath = join(contentDirectory, "navigation.json");
const entriesByDirectory = new Map<string, Map<string, string>>();

const navigation = parseNavigation(JSON.parse(await readFile(navigationPath, "utf8")));
addEntry("", "index", "API reference");

await normalizeGeneratedLinks(contentDirectory);

for (const item of navigation) {
  collectNavigation(item);
}

for (const [directory, entries] of entriesByDirectory) {
  const outputDirectory = resolve(contentDirectory, directory);
  if (
    outputDirectory !== contentDirectory &&
    !outputDirectory.startsWith(`${contentDirectory}${sep}`)
  ) {
    throw new Error(`Refusing to write API navigation metadata outside ${contentDirectory}`);
  }
  await mkdir(outputDirectory, { recursive: true });
  const source = `// Generated by scripts/generate-api-reference-meta.ts. Do not edit.\nexport default ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n`;
  await writeFile(join(outputDirectory, "_meta.ts"), source);
}

async function normalizeGeneratedLinks(directory: string): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      await normalizeGeneratedLinks(path);
    } else if (entry.isFile() && extname(entry.name) === ".mdx") {
      const source = await readFile(path, "utf8");
      const normalized = normalizeGeneratedMarkdownLinks(source);
      await writeFile(path, normalized);
    }
  }
}

function collectNavigation(item: NavigationItem): void {
  if (item.path !== undefined) {
    addPath(item.path, formatNavigationTitle(item.title, item.path));
  } else {
    const firstChildPath = item.children?.find((child) => child.path !== undefined)?.path;
    if (firstChildPath !== undefined) {
      const groupDirectory = posix.dirname(firstChildPath);
      addEntry(
        posix.dirname(groupDirectory),
        posix.basename(groupDirectory),
        formatNavigationTitle(item.title),
      );
    }
  }

  for (const child of item.children ?? []) {
    collectNavigation(child);
  }
}

function addPath(path: string, title: string): void {
  const { directory, name } = navigationPathParts(path);

  addEntry(directory === "." ? "" : directory, name, title);
  if (name === "index" && directory !== ".") {
    const parent = posix.dirname(directory);
    addEntry(parent === "." ? "" : parent, posix.basename(directory), title);
  }
}

function addEntry(directory: string, name: string, title: string): void {
  let entries = entriesByDirectory.get(directory);
  if (entries === undefined) {
    entries = new Map();
    entriesByDirectory.set(directory, entries);
  }
  entries.set(name, title);
}

function parseNavigation(value: unknown): readonly NavigationItem[] {
  if (!Array.isArray(value) || !value.every(isNavigationItem)) {
    throw new Error(`Invalid TypeDoc navigation JSON at ${navigationPath}`);
  }
  return value;
}

function isNavigationItem(value: unknown): value is NavigationItem {
  if (typeof value !== "object" || value === null || !("title" in value)) {
    return false;
  }
  if (typeof value.title !== "string") {
    return false;
  }
  if ("path" in value && value.path !== undefined && typeof value.path !== "string") {
    return false;
  }
  if ("path" in value && value.path !== undefined && !isValidNavigationPath(value.path)) {
    return false;
  }
  if ("children" in value && value.children !== undefined) {
    return Array.isArray(value.children) && value.children.every(isNavigationItem);
  }
  return true;
}
