import { readFile, writeFile } from "node:fs/promises";

const packageJsonPath = new URL("../packages/mcp/package.json", import.meta.url);
const serverJsonPath = new URL("../packages/mcp/server.json", import.meta.url);
const versionModulePath = new URL("../packages/mcp/src/version.ts", import.meta.url);

const packageJson: unknown = JSON.parse(await readFile(packageJsonPath, "utf8"));
const serverJson: unknown = JSON.parse(await readFile(serverJsonPath, "utf8"));

if (
  !isRecord(packageJson) ||
  typeof packageJson.name !== "string" ||
  typeof packageJson.version !== "string"
) {
  throw new Error("packages/mcp/package.json must contain string name and version fields");
}
if (!isRecord(serverJson) || !Array.isArray(serverJson.packages)) {
  throw new Error("packages/mcp/server.json must contain a packages array");
}

const matchingPackages = serverJson.packages.filter(
  (entry) =>
    isRecord(entry) && entry.registryType === "npm" && entry.identifier === packageJson.name,
);
if (matchingPackages.length !== 1) {
  throw new Error("packages/mcp/server.json must contain exactly one matching npm package");
}

const npmPackage = matchingPackages[0];
serverJson.version = packageJson.version;
npmPackage.version = packageJson.version;
await writeFile(serverJsonPath, `${JSON.stringify(serverJson, null, 2)}\n`);
await writeFile(
  versionModulePath,
  `// Generated by scripts/sync-mcp-registry-metadata.ts during package versioning.\nexport const PACKAGE_VERSION = ${JSON.stringify(packageJson.version)};\n`,
);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
