/**
 * Conversion helpers for the raw OOXML escape hatch.
 *
 * Elements that PptxSourceModel does not represent as typed nodes, such as unsupported
 * fills, effects, and extensions, are saved as `RawOoxmlNode` / `RawSidecar` values for
 * structural round-tripping. Plain objects generated by fast-xml-parser are converted
 * into raw trees while preserving qualified names.
 */

import type { RawOoxmlNode, RawSidecar, RawSidecarId } from "../source/index.js";
import { asRawSidecarId } from "../source/index.js";
import { unsafeOoxmlBoundaryAssertion } from "../unsafe-type-assertion.js";
import { localName, type XmlNode } from "./xml.js";

const ATTR_PREFIX = "@_";
const TEXT_KEY = "#text";

/** Creates a factory that issues stable raw sidecar ids per part. */
export function createSidecarIdFactory(partPath: string): () => RawSidecarId {
  let counter = 0;
  return () => asRawSidecarId(`${partPath}#raw-${counter++}`);
}

/**
 * Convert the element value generated by fast-xml-parser to `RawOoxmlNode`. `name` is
 * qualified name (Example: `a:effectLst`).attributes are kept after removing the `@_` prefix,
 * `#text` is retained as text content.
 */
function xmlValueToRawNode(name: string, value: unknown): RawOoxmlNode {
  if (typeof value !== "object" || value === null) {
    const text = scalarText(value);
    return text !== undefined && text !== "" ? { name, text } : { name };
  }

  const obj = unsafeOoxmlBoundaryAssertion<Record<string, unknown>>(value);
  const attributes: Record<string, string> = {};
  const children: RawOoxmlNode[] = [];
  let text: string | undefined;

  for (const key of Object.keys(obj)) {
    if (key === TEXT_KEY) {
      text = scalarText(obj[key]);
      continue;
    }
    if (key.startsWith(ATTR_PREFIX)) {
      const attrValue = scalarText(obj[key]);
      if (attrValue !== undefined) attributes[key.slice(ATTR_PREFIX.length)] = attrValue;
      continue;
    }
    const childValue = obj[key];
    const items = Array.isArray(childValue) ? childValue : [childValue];
    for (const item of items) {
      children.push(xmlValueToRawNode(key, item));
    }
  }

  return {
    name,
    ...(Object.keys(attributes).length > 0 ? { attributes } : {}),
    ...(children.length > 0 ? { children } : {}),
    ...(text !== undefined && text !== "" ? { text } : {}),
  };
}

/** Single child element (qualified `name` / value) to one raw sidecar. */
export function makeSidecar(
  name: string,
  value: unknown,
  nextId: () => RawSidecarId,
  orderingSlot?: number,
): RawSidecar {
  return {
    id: nextId(),
    node: xmlValueToRawNode(name, value),
    ...(orderingSlot !== undefined ? { orderingSlot } : {}),
  };
}

/**
 * Children of the parent element that are not included in `knownLocalNames` (= not interpreted as typed)
 * Collect everything as a raw sidecar. Attribute keys and text keys are not applicable.
 * Record the appearance order of the children as `orderingSlot` in preparation for restoring the order when writing back.
 */
export function collectUnknownSidecars(
  parent: XmlNode | undefined,
  knownLocalNames: ReadonlySet<string>,
  nextId: () => RawSidecarId,
): RawSidecar[] {
  if (!parent) return [];
  const sidecars: RawSidecar[] = [];
  let slot = 0;
  for (const key of Object.keys(parent)) {
    if (key.startsWith(ATTR_PREFIX) || key === TEXT_KEY) continue;
    const value = parent[key];
    const items = Array.isArray(value) ? value : [value];
    if (knownLocalNames.has(localName(key))) {
      slot += items.length;
      continue;
    }
    for (const item of items) {
      sidecars.push(makeSidecar(key, item, nextId, slot));
      slot++;
    }
  }
  return sidecars;
}

function scalarText(value: unknown): string | undefined {
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return undefined;
}
